### ISSUE TITLE
[BUG] crash on Mac Chrome with 81MB file

### ISSUE THREAD

**Issue by ldenoue** [FL33TW00D/whisper-turbo#25]
**Describe the bug**

**To Reproduce**
1. Go to https://whisper-turbo.com/
2. Click on Tiny
3. Upload the amazon.mp3 file (56 minutes 29 seconds long)
![image](https://github.com/FL33TW00D/whisper-turbo/assets/149561/40898257-e928-4c16-806a-a317aca7e71d)

```
269-03125f41d949514b.js:1 panicked at crates/whisper-core/src/decoding.rs:85:17:
index out of bounds: the len is 509 but the index is 4294967295

Stack:

Error
    at t.wbg.__wbg_new_abda76e883ba8a5f (https://whisper-turbo.com/_next/static/chunks/269-03125f41d949514b.js:1:17434)
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[2029]:0x2e31ac
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[2722]:0x2fafdf
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[2364]:0x2f313a
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[756]:0x22edd9
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[241]:0x9662c
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[1241]:0x28f015
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.d05673f1.wasm:wasm-function[2935]:0x2fd7f4
    at m (https://whisper-turbo.com/_next/static/chunks/269-03125f41d949514b.js:1:13180)
    at _ (https://whisper-turbo.com/_next/static/chunks/269-03125f41d949514b.js:1:13056)


t.wbg.__wbg_error_f851667af71bcfc6 @ 269-03125f41d949514b.js:1
$func2029 @ whisper-webgpu_bg.d05673f1.wasm:0x2e3279
$func2722 @ whisper-webgpu_bg.d05673f1.wasm:0x2fafdf
$func2364 @ whisper-webgpu_bg.d05673f1.wasm:0x2f313a
$func756 @ whisper-webgpu_bg.d05673f1.wasm:0x22edd9
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x9662c
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_f7e06ee3c11698eb @ 269-03125f41d949514b.js:2
$func2048 @ whisper-webgpu_bg.d05673f1.wasm:0x2e41e7
$func2185 @ whisper-webgpu_bg.d05673f1.wasm:0x2ea92e
$func502 @ whisper-webgpu_bg.d05673f1.wasm:0x1c5ee0
$func2112 @ whisper-webgpu_bg.d05673f1.wasm:0x2e7485
$func1553 @ whisper-webgpu_bg.d05673f1.wasm:0x2c3fd5
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1
Promise.then (async)
t.wbg.__wbg_then_b2267541e2a73865 @ 269-03125f41d949514b.js:2
$func1507 @ whisper-webgpu_bg.d05673f1.wasm:0x2c027d
$func238 @ whisper-webgpu_bg.d05673f1.wasm:0x8b780
$func241 @ whisper-webgpu_bg.d05673f1.wasm:0x962ae
$func1241 @ whisper-webgpu_bg.d05673f1.wasm:0x28f015
$__wbindgen_export_3 @ whisper-webgpu_bg.d05673f1.wasm:0x2fd7f4
m @ 269-03125f41d949514b.js:1
_ @ 269-03125f41d949514b.js:1

```

**Desktop (please complete the following information):**
 - OS: [MacOS Monterey 12.6 (21G115)]
 - Browser [Version 117.0.5938.88 (Official Build) (x86_64)]

**Comment by FL33TW00D** [comment]
Determined the cause, and will ship a fix today 🤞

**Comment by ldenoue** [comment]
Verified that it is fixed, thank you!

**Comment by DavidGOrtega** [comment]
I have tried a file containing 37:10 min of audio stereo 44,1kHz (53.7MB) extracted randomly from youtube using the [remote playground](https://whisper-turbo.com/) the model consistently stops the transcription at 

```json
"start":509.04,"stop":512.68,"last":false}]}
```

remaining 2/3 parts of the audio still

**Comment by FL33TW00D** [comment]
> I have tried a file containing 37:10 min of audio stereo 44,1kHz (53.7MB) extracted randomly from youtube using the [remote playground](https://whisper-turbo.com/).
> 
> The model consistently stops the transcription at
> 
> ```json
> "start":509.04,"stop":512.68,"last":false}]}
> ```
> 
> remaining 2/3 parts of the audio still to be done

Which model?

100% a bug, please attach the audio or send the file to chris@fleetwood.dev

**Comment by DavidGOrtega** [comment]
> Successfully transcribed a 1h27m clip using Tiny.

I used tiny as you did. Im sending you the audio file.

**Comment by FL33TW00D** [comment]
> I sent you an email with the audio file. I has a very concise unfriendly message (zero words) but a helpful and descriptive subject: "Audio file not working"
> 
> Please forgive my rushed human abilities 🤣

youtube-audio.mp3 works great with the new 0.8.0 release on Tiny + MacOS + Chrome 118!
Let me know if it's not working for your system.

**Comment by DavidGOrtega** [comment]
@FL33TW00D works perfectly!
