### ISSUE TITLE
[BUG] WAVE and WEBM crashes whisper-turbo

### ISSUE THREAD

**Issue by DavidGOrtega** [FL33TW00D/whisper-turbo#56]
This issue has two problems:

 - [ ] Weak handling of wav and webm files (despite fixing the duration in webm)
 - [ ] Uncaught in promise that makes js unable to catch the failure ending up in unhandled situations 

The same youtube-news file that we used previously converted into wav or wav16 makes whisper.turbo to crash without any error handling possible . Im sending the files to your email

```
462.98ecf0d3854ca5c4.js:2 panicked at crates/whisper-core/src/logit_mutators/timestamp_rules.rs:87:62:
called `Result::unwrap()` on an `Err` value: UndefinedOrder

Stack:

Error
    at t.wbg.__wbg_new_abda76e883ba8a5f (https://whisper-turbo.com/_next/static/chunks/462.98ecf0d3854ca5c4.js:2:1742)
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[2328]:0x34911a
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[3093]:0x363550
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[2642]:0x356fdc
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[231]:0x48347
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[236]:0x5d1db
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[1419]:0x2eeb7a
    at https://whisper-turbo.com/_next/static/media/whisper-webgpu_bg.1f358181.wasm:wasm-function[3315]:0x365fc6
    at x (https://whisper-turbo.com/_next/static/chunks/462.98ecf0d3854ca5c4.js:1:4056)
    at o (https://whisper-turbo.com/_next/static/chunks/462.98ecf0d3854ca5c4.js:1:3932)


t.wbg.__wbg_error_f851667af71bcfc6 @ 462.98ecf0d3854ca5c4.js:2
$func2328 @ whisper-webgpu_bg.1f358181.wasm:0x3491e7
$func3093 @ whisper-webgpu_bg.1f358181.wasm:0x363550
$func2642 @ whisper-webgpu_bg.1f358181.wasm:0x356fdc
$func231 @ whisper-webgpu_bg.1f358181.wasm:0x48347
$func236 @ whisper-webgpu_bg.1f358181.wasm:0x5d1db
$func1419 @ whisper-webgpu_bg.1f358181.wasm:0x2eeb7a
$__wbindgen_export_3 @ whisper-webgpu_bg.1f358181.wasm:0x365fc6
x @ 462.98ecf0d3854ca5c4.js:1
o @ 462.98ecf0d3854ca5c4.js:1
whisper-webgpu_bg.1f358181.wasm:0x349230 Uncaught RuntimeError: unreachable
    at whisper-webgpu_bg.1f358181.wasm:0x349230
    at whisper-webgpu_bg.1f358181.wasm:0x363550
    at whisper-webgpu_bg.1f358181.wasm:0x356fdc
    at whisper-webgpu_bg.1f358181.wasm:0x48347
    at whisper-webgpu_bg.1f358181.wasm:0x5d1db
    at whisper-webgpu_bg.1f358181.wasm:0x2eeb7a
    at whisper-webgpu_bg.1f358181.wasm:0x365fc6
    at x (462.98ecf0d3854ca5c4.js:1:4056)
    at o (462.98ecf0d3854ca5c4.js:1:3932)
```

Minimum whisper code:

```js
import * as whisper from 'whisper-webgpu';
 ...

try {
 await whisper.default();
 const builder = new whisper.SessionBuilder();
 const session = await builder.setModel(model).setTokenizer(tokenizer).build();
 const segments = await session.run(audio).catch(err => { throw err }); 
} catch(err) {
  // never enters here
}
```

Macos M1 16GB Ventura 13.1
Chromium 118.0.5993.32

**Comment by FL33TW00D** [comment]
@DavidGOrtega
Thank you for the thorough report!

You're right - there is currently poor handling of 3 things:
1. WAVs that aren't 16khz need to be resampled, and they're currently not. I will raise a separate issue for that.  I'll double check with the file you've sent and make sure it's a known issue.
3. WEBM is unfortunately going to have to be rejected, I don't have an easy way of supporting it.
5. Error handling is very poor - I will try and surface at least somewhat useful errors in 0.11.0.

Thanks for sticking with me,
Chris

**Comment by FL33TW00D** [comment]
@DavidGOrtega 
I've just tested all 3 files you provided.
1. `youtube-news16k.wav` worked great for me, did it fail for you?
2. `youtube-news.wav` is poorly handled as stated above, I will ship resampling in 0.11.0.
3. `youtube-news.mp3` worked great for me too. Let me know if it failed.

Apologies for taking your time, the resampling will be fixed shortly.

Chris

**Comment by DavidGOrtega** [comment]
@FL33TW00D nothing to regret! Your library is great!

> youtube-news.mp3 worked great for me too. Let me know if it failed.

Yes, the issue is only confirmed with wav and webm

> youtube-news16k.wav worked great for me, did it fail for you?

<img width="1438" alt="image" src="https://github.com/FL33TW00D/whisper-turbo/assets/414967/c34d6db2-174e-4367-a418-abc47e47e170">

Yes, check the file converted at 16k

<img width="305" alt="image" src="https://github.com/FL33TW00D/whisper-turbo/assets/414967/8af92262-f4bb-4e99-b3ed-f131c3e56d90">

**Comment by FL33TW00D** [comment]
> @FL33TW00D nothing to regret! Your library is great!
> 
> > youtube-news.mp3 worked great for me too. Let me know if it failed.
> 
> Yes, the issue is only confirmed with wav and webm
> 
> > youtube-news16k.wav worked great for me, did it fail for you?
> 
> <img alt="image" width="1438" src="https://user-images.githubusercontent.com/414967/284943211-c34d6db2-174e-4367-a418-abc47e47e170.png">
> Yes, check the file converted at 16k
> 
> <img alt="image" width="305" src="https://user-images.githubusercontent.com/414967/284943828-8af92262-f4bb-4e99-b3ed-f131c3e56d90.png">

Just tested with the base model and can see it fails.
Will dig deeper and report back.

**Comment by FL33TW00D** [comment]
@DavidGOrtega Base model should be fixed in the latest release.

Will have to think more about WebM, doesn't seem easy without an audio handling rewrite.

**Comment by jozefchutka** [comment]
An idea for resampling - re-encoding:

I would recommend to keep whisper related code separated from resampling libs. This way the core lib can be smaller, with less distractions and bugs while better maintainable.

Resampling / re-encoding to pcm can be done via some existing mature tools that can be scheduled before whisper-turbo is engaged. I would recommend an optimised port of [ffmpeg wasm](https://ffmpeg.wide.video/) that would only include audio decoders. With ffmpeg, following command can be used to produce raw_audio data for whisper-turbo:

```
ffmpeg -i input.webm -acodec pcm_s16le -ar 16000 -ac 1 out.pcm
```

**Comment by FL33TW00D** [comment]
Thanks for the suggestion from @jozefchutka, I've implemented this on `ratchet`: https://github.com/FL33TW00D/ratchet/blob/master/examples/ratchet-whisper/src/app/page.tsx#L68
